default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_el_gaucho_nyheter_development

test:
  <<: *default
  database: api_el_gaucho_nyheter_test

production:
  <<: *default
  database: api_el_gaucho_nyheter_production
  username: api_el_gaucho_nyheter
  password: <%= ENV['API_EL_GAUCHO_NYHETER_DATABASE_PASSWORD'] %>
